name: ci

on: pull_request

jobs:
  lint:
    runs-on:          ubuntu-latest
    timeout-minutes:  10
    steps:
      - { name: checkout                    , uses: actions/checkout@v2       }
      - { name: lint                        , uses: stefanoeb/eslint-action@1.0.2 }

  ci:
    needs:            lint
    strategy:
      matrix:
        os:           [ ubuntu ] #, windows ] - does not support containers yet :(
        node:         [ 13, 12, 10 ]
        mongo:        [ 4, 3 ]
        redis:        [ 5, 4 ]
    runs-on:          ${{ matrix.os }}-latest
    timeout-minutes:  10
    steps:
      - { name: checkout                    , uses: actions/checkout@v2 }
      - { name: get-versi                   , run:  'npm i versi --no-save'   }
      - name: node v${{ matrix.node }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - name: mongo start
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongo }}
      - name: redis start
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis }}
      - { name: env-info                    , run: 'npx envinfo'              }
      - { name: install                     , run: 'npm i'                    }
      - { name: test                        , run: 'npm test'                 }
      - { name: cover                       , run: 'npm run cover'            }
      - { name: archive                     , run: 'tar -czvf ci-results.tar.gz coverage' }
      - name: save
        uses: actions/upload-artifact@v1
        with:
          name: ci-results.os-${{ matrix.os }}.node-${{ matrix.node }}.mongo-${{ matrix.mongo }}.redis-${{ matrix.redis }}
          path: ci-results.tar.gz
      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ci-results.os-${{ matrix.os }}.node-${{ matrix.node }}.mongo-${{ matrix.mongo }}.redis-${{ matrix.redis }}
          parallel: true

  coveralls-end:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: coveralls-end
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
